 ----------------DIGITAL_MARKETING_SQL_PROJECT-----------------


SELECT * FROM neharawat.digitalmarketingdataset;


---- Which campaigns achieved at least 100 leads?----
select campaign_name, leads
from digitalmarketingdataset
where leads > 100;
 
 
 ----- List the top 5 campaigns by orders ------ 
 select campaign_name , orders
 from digitalmarketingdataset
 order by orders desc
 limit 5;
 
 ---- Which campaigns had a cost-per-click (CPC) greater than $10? CPC = Mark_Spent / Clicks---- 
 select campaign_name, round(mark_spent/clicks,2) as CPC
 from digitalmarketingdataset
 where mark_spent/clicks > 10;
 
 
 ---- Identify campaigns with no orders despite having clicks.----- 
 select campaign_name, clicks, orders
 from digitalmarketingdataset
 where clicks> 0 and orders = 0;
 
 
 ---- Find campaigns that had a revenue-to-spend ratio above 3.0. Revenue-to-Spend = Revenue / Mark_Spent----- 
 select campaign_name, revenue/mark_spent as revenue_to_spend 
 from digitalmarketingdataset
 where revenue/mark_spent >3.0;
 
 
 ---- What is the total number of impressions by category?----- 

 SELECT category, SUM(impressions) AS total_impressions
FROM digitalmarketingdataset
GROUP BY category
ORDER BY total_impressions DESC;


---- Which category had the lowest average cost per order (CPO)? CPO = Mark_Spent / Orders?---- 
select category, avg(mark_spent/ nullif(orders, 0)) as avg_cpo
from digitalmarketingdataset
group by category
order by avg_cpo
limit 1;

---- What is the total revenue generated by each category?----- 
select sum(revenue) , category
from digitalmarketingdataset
group by category;

---- Find the average revenue per campaign for each date------ 
select avg(revenue), c_date
from digitalmarketingdataset
group by c_date
order by avg(revenue) desc;

----  Which month had the highest total marketing spend? -----  
SELECT date_format(c_date,'%m') AS month, SUM(mark_spent) AS total_spent
FROM digitalmarketingdataset
GROUP BY month
ORDER BY total_spent DESC
LIMIT 1;

------ Which campaigns had a conversion rate (orders/impressions) above 1%?----- 
select campaign_name, (orders * 100.0 /impressions) as conversion_rate
from digitalmarketingdataset
where (orders * 100.0/impressions) >1
order by conversion_rate desc ;

----- What is the average lead-to-order ratio for all campaigns? Lead-to-Order = Orders / Leads ---- 
select avg(orders/nullif(leads,0)) as avg_lead_to_order_ratio from digitalmarketingdataset;


----- Find campaigns where the cost per lead (CPL) is the lowest. CPL = Mark_Spent / Leads ------ 
select campaign_name, mark_spent/(nullif(leads,0)) as CPL
from digitalmarketingdataset
where leads>0
order by mark_spent/(nullif(leads,0)) 
limit 5;


----- Which campaigns had no leads but generated revenue?----- 
select campaign_name
from digitalmarketingdataset
where leads = 0 and revenue > 0;

------ Determine the best-performing campaign by ROI on each date.------ 
select campaign_name, ((revenue - mark_spent)* 100.0 / mark_spent )as ROI, c_date
from digitalmarketingdataset
order by  ROI desc;


------ What is the total revenue, total spend, and ROI for all campaigns combined?----- 
select sum(revenue) as total_revenue, sum(mark_spent) as total_spend , (sum(revenue) - sum(mark_spent)* 100.0 / sum(mark_spent ))as ROI
from digitalmarketingdataset;


---- How many campaigns exceeded $10,000 in marketing spend? ----- 
select campaign_name, mark_spent
from digitalmarketingdataset
where mark_spent > 10000;

------- What is the average impressions-per-click for each category?----- 
SELECT category, AVG(impressions * 1.0 / NULLIF(clicks, 0)) AS impressions_per_click
FROM digitalmarketingdataset
GROUP BY category;
